apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - base/repository.yaml
  - base/applications.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.12.1

patches:
  - path: overlays/argocd-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
